# -*- coding: utf-8 -*-
"""tarea programada f3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfAqo3TU1K-xlg9kZCCDdz6pMXYJd3X1
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from mpl_toolkits.mplot3d import Axes3D

def dipolo_magnetico(x, tau):
    """
    X, Y, Z = posiciones normalizadas
    dX, dY, dZ = velocidades normalizadas
    τ  = tiempo normalizado
    """
    X, dX, Y, dY, Z, dZ = x #vector que tiene la posicion y velocidad en cada eje

    r2 = X**2 + Y**2 + Z**2 #r^2, distancia al cuadrado desde el origen

    r5 = r2**(5/2)

    # ecuaciones diferenciales que describen las aceleraciones derivadas de la fuerza de Lorentz
    d2X = ((2*Z**2 - Y**2 - X**2)*dY - 3*Y*Z*dZ) / r5
    d2Y = -((2*Z**2 - Y**2 - X**2)*dX - 3*X*Z*dZ) / r5
    d2Z = 3*Z*(Y*dX - X*dY) / r5

    return [dX, d2X, dY, d2Y, dZ, d2Z]

x0_dipolo = [1, 0.005, 1, 0.005, 0, 0.01] #posiciones y velocidades iniciales en cada eje

# solución para diferentes escalas de tiempo

# solucion para el movimiento en Z con un tau maximo de 1400
# se utiliza odeint para resolver el sistema de EDOs en el intervalo indicado
tau_z = np.linspace(0, 1400, 5000)
sol_z = odeint(dipolo_magnetico, x0_dipolo, tau_z)

# cálculo del error en energía, ya que sabemos que se deberia mantener constante
# entonces nos permite ver que tan exacta es la aproximacion numerica
E0_z = sol_z[0, 1]**2 + sol_z[0, 3]**2 + sol_z[0, 5]**2
Ef_z = sol_z[-1, 1]**2 + sol_z[-1, 3]**2 + sol_z[-1, 5]**2
error_z = abs((Ef_z - E0_z)/E0_z) * 100
print(f"Error en energía en Z: {error_z:.3f}%")

# movimiento en XY con tau maximo de 26000, se aplica la misma logica que
# en el anterior
tau_xy = np.linspace(0, 26000, 10000)
sol_xy = odeint(dipolo_magnetico, x0_dipolo, tau_xy)

E0_xy = sol_xy[0, 1]**2 + sol_xy[0, 3]**2 + sol_xy[0, 5]**2
Ef_xy = sol_xy[-1, 1]**2 + sol_xy[-1, 3]**2 + sol_xy[-1, 5]**2
error_xy = abs((Ef_xy - E0_xy)/E0_xy) * 100
print(f"Error en energía en XY: {error_xy:.3f}%")

# a partir de aca se desarrolla la grafica
fig = plt.figure(figsize=(15, 10))
ax3 = fig.add_subplot(2, 3, 3, projection='3d')
ax3.plot(sol_xy[:, 0], sol_xy[:, 2], sol_xy[:, 4])  # X = col 0, Y = col 2, Z = col 4

ax3.grid()
ax3.set_xlabel('X')
ax3.set_ylabel('Y')
ax3.set_zlabel('Z')
ax3.set_title('Movimiento en un dipolo magnético')

ax3.set_xlim([-2, 2])
ax3.set_ylim([-2, 2])
ax3.set_zlim([-1, 1])
ax3.set_box_aspect([1, 1, 1])

plt.tight_layout()
plt.savefig('DipoloMagnetico.png', dpi=150, bbox_inches='tight')
plt.show()


def campo_no_uniforme(x, tau, D):
    X, Y, dY, Z, dZ = x

    dX = (1 + Z)*Y + D
    d2Y = -(1 + Z)**2 * Y - D*(1 + Z)
    d2Z = -(1 + Z)*Y**2 - D*Y

    return [dX, dY, d2Y, dZ, d2Z]

# se aplican las siguientes condiciones iniciales, basandose en la referencia
# indicada en el reporte
Y0 = 0.66
Ux = 0.02
Uz = 0.08
x0_campo = [0, Y0, 0, 0, Uz]
D = Ux - Y0
tf = 140
tau_campo = np.linspace(0, tf, 2000)

# solucion
sol_campo = odeint(campo_no_uniforme, x0_campo, tau_campo, args=(D,))

# calculo de las energias
energia = ((1 + sol_campo[:, 3])*sol_campo[:, 1] + D)**2 + sol_campo[:, 2]**2 + sol_campo[:, 4]**2
energia_inicial = Ux**2 + Uz**2

print(f"\nEnergía inicial: {energia_inicial:.4f}")
print(f"Energía final: {energia[-1]:.4f}")
print(f"Diferencia: {abs(energia[-1] - energia_inicial):.6f}")


fig2 = plt.figure(figsize=(15, 5))

# Trayectoria 3D
idx_max = np.argmax(sol_campo[:, 3])
ax = fig2.add_subplot(1, 3, 1, projection='3d')
ax.plot(sol_campo[:, 0], sol_campo[:, 1], sol_campo[:, 3])
ax.scatter([sol_campo[0, 0]], [sol_campo[0, 1]], [sol_campo[0, 3]],
            color='green', s=100, label='Inicio')
ax.scatter([sol_campo[idx_max, 0]], [sol_campo[idx_max, 1]], [sol_campo[idx_max, 3]],
            color='red', s=100, label='Z máximo')
ax.grid(True)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title('Trayectoria X,Y,Z')
ax.view_init(20, 40)
ax.legend()

plt.tight_layout()
plt.savefig('CampoNoUniforme.png', dpi=150, bbox_inches='tight')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import FuncAnimation
import time
from matplotlib import cm

# esta funcion es para que la tierra parezca la tierra y no una bola azul
# no afecta en nada a la simulacion

def crear_textura_tierra(resolucion=100):
    u = np.linspace(0, 2 * np.pi, resolucion)
    v = np.linspace(0, np.pi, resolucion)
    U, V = np.meshgrid(u, v)

    # se convierte a coordenadas lat/lon
    latitud = 90 - np.degrees(V)  # Latitud: 90 (polo norte) a -90 (polo sur)
    longitud = np.degrees(U)  # Longitud: 0 a 360

    # oceanos
    colores = np.ones((resolucion, resolucion, 3))
    colores[:, :, 0] = 0.1
    colores[:, :, 1] = 0.3
    colores[:, :, 2] = 0.6

    # aqui se hace una mascara de los continentes
    mascara_america = (
        ((longitud > 190) & (longitud < 290) & (latitud > 10) & (latitud < 70)) |  # Norte America
        ((longitud > 210) & (longitud < 280) & (latitud > -55) & (latitud < 15))    # Sur America
    )

    mascara_europa = (
        (longitud > 350) | (longitud < 40)
    ) & (latitud > 35) & (latitud < 70)

    mascara_africa = (
        (longitud > 345) | (longitud < 50)
    ) & (latitud > -35) & (latitud < 38)

    mascara_asia = (
        ((longitud > 40) & (longitud < 150) & (latitud > 10) & (latitud < 75)) |  # Asia continental
        ((longitud > 90) & (longitud < 120) & (latitud > -10) & (latitud < 25))    # Sudeste asiatico
    )

    mascara_australia = (
        (longitud > 110) & (longitud < 155) & (latitud > -45) & (latitud < -10)
    )

    mascara_antartida = (latitud < -60)

    mascara_tierra = (mascara_america | mascara_europa | mascara_africa |
                      mascara_asia | mascara_australia | mascara_antartida)

    # aqui les pongo color
    colores[mascara_tierra, 0] = 0.2 + 0.2 * np.random.rand(np.sum(mascara_tierra))
    colores[mascara_tierra, 1] = 0.5 + 0.2 * np.random.rand(np.sum(mascara_tierra))
    colores[mascara_tierra, 2] = 0.1 + 0.1 * np.random.rand(np.sum(mascara_tierra))

    colores[mascara_antartida, 0] = 0.9
    colores[mascara_antartida, 1] = 0.95
    colores[mascara_antartida, 2] = 1.0

    # aqui se agregan nubes
    mascara_nubes = np.random.rand(resolucion, resolucion) > 0.7
    intensidad_nubes = np.random.rand(resolucion, resolucion) * 0.3

    colores[mascara_nubes] = colores[mascara_nubes] + intensidad_nubes[mascara_nubes][:, np.newaxis]
    colores = np.clip(colores, 0, 1)

    return colores


# aqui ya empieza lo importante

class SimulacionCinturonVanAllen:
    def __init__(self):
        self.radio_tierra = 1.0  # radio terrestre normalizado para simplificar
        self.radio_cinturon_interno = 1.5 * self.radio_tierra  # cinturon interno (protones)
        self.radio_cinturon_externo = 4.0 * self.radio_tierra  # cinturon externo (electrones)

    def generar_trayectoria_espiral(self, tipo_particula, radio_cinturon, duracion=100):

        # se definen distintos parametros para la espiral segun el tipo de particula
        if tipo_particula == 'electron':
            radio_helice = 0.15  # radio de la espiral
            velocidad_rotacion = 8.0  # velocidad angular
            velocidad_rebote = 0.5   # velocidad de rebote
            velocidad_deriva = 0.015  # velocidad de deriva
            color = 'red'
            alfa = 0.8
        else:  # solo puede ser proton
            radio_helice = 0.25
            velocidad_rotacion = 3.0
            velocidad_rebote = 0.3
            velocidad_deriva = 0.008
            color = 'cyan'
            alfa = 0.8

        # Angulo inicial aleatorio
        theta0 = np.random.uniform(0, 2*np.pi)
        phi0 = np.random.uniform(-0.3, 0.3)  # se define un angulo inicial cerca del ecuador

        # con este parametro se determinan las lineas de campo magnetico
        parametro_L = radio_cinturon / self.radio_tierra

        # array de tiempo
        tiempo = np.linspace(0, duracion, 400)

        # aqui se define el movimiento de rebote, que hace que la particula oscile entre norte y sur
        lambda_max = np.arccos(np.sqrt(1/parametro_L)) * 0.85  # este es el angulo maximo de latitud
        movimiento_rebote = lambda_max * np.sin(velocidad_rebote * tiempo) # esta es la ecuacion de movimiento

        # aqui se define el movimiento de deriva, que hace que la particula se mueva longitudinalmente
        theta_deriva = theta0 + velocidad_deriva * tiempo

        # aqui se definen las coordenadas del centro de la espiral con coordenadas esfericas para las lineas de campo
        phi_centro = np.pi/2 - movimiento_rebote  # complemento de la latitud
        radio_centro = parametro_L * np.cos(movimiento_rebote)**2  # radio en funcion de la latitud

        # aqui se define el centro de la espiral en cartesianas
        x_centro = radio_centro * np.sin(phi_centro) * np.cos(theta_deriva)
        y_centro = radio_centro * np.sin(phi_centro) * np.sin(theta_deriva)
        z_centro = radio_centro * np.cos(phi_centro)

        # aqui se agrega el angulo de rotacion por la velocidad angular
        angulo_espiral = velocidad_rotacion * tiempo

        # aqui se definen los distintos vectores que hace que se cree la trayectoria espiral
        # se define un vector tangente con el gradiente
        dx = np.gradient(x_centro)
        dy = np.gradient(y_centro)
        dz = np.gradient(z_centro)
        norma = np.sqrt(dx**2 + dy**2 + dz**2) + 1e-10
        dx, dy, dz = dx/norma, dy/norma, dz/norma

        # se define un primer vector perpendicular arbitrario
        perp1_x = -dy
        perp1_y = dx
        perp1_z = np.zeros_like(dx)
        norma1 = np.sqrt(perp1_x**2 + perp1_y**2 + perp1_z**2) + 1e-10
        perp1_x, perp1_y, perp1_z = perp1_x/norma1, perp1_y/norma1, perp1_z/norma1

        # un segundo vector perpendicular con el producto cruz de los primeros dos
        perp2_x = dy * perp1_z - dz * perp1_y
        perp2_y = dz * perp1_x - dx * perp1_z
        perp2_z = dx * perp1_y - dy * perp1_x

        # esta ya seria la posicion final de la espiral
        x_espiral = x_centro + radio_helice * (np.cos(angulo_espiral) * perp1_x +
                                               np.sin(angulo_espiral) * perp2_x)
        y_espiral = y_centro + radio_helice * (np.cos(angulo_espiral) * perp1_y +
                                               np.sin(angulo_espiral) * perp2_y)
        z_espiral = z_centro + radio_helice * (np.cos(angulo_espiral) * perp1_z +
                                               np.sin(angulo_espiral) * perp2_z)

        return {
            'x': x_espiral,
            'y': y_espiral,
            'z': z_espiral,
            'color': color,
            'alfa': alfa,
            'radio_helice': radio_helice
        }


#aqui ya empieza la simulacion principal

def simulacion_van_allen():
    tiempo_inicio = time.time()

    # se crea el simulador
    simulacion = SimulacionCinturonVanAllen()

    # se generan las particulas
    num_electrones = 4
    num_protones = 4

    # aqui se generan las trayectorias para cada una de las particulas
    trayectorias_electrones = [
        simulacion.generar_trayectoria_espiral('electron', simulacion.radio_cinturon_externo, duracion=100)
        for _ in range(num_electrones)
    ]
    trayectorias_protones = [
        simulacion.generar_trayectoria_espiral('proton', simulacion.radio_cinturon_interno, duracion=100)
        for _ in range(num_protones)
    ]

    # aqui se empieza a generar la figura
    figura = plt.figure(figsize=(16, 12))
    eje = figura.add_subplot(111, projection='3d')

    # aqui se crea la tierra y se le pone la textura que hice al puro principio
    resolucion = 100
    u = np.linspace(0, 2 * np.pi, resolucion)
    v = np.linspace(0, np.pi, resolucion)

    x_tierra = simulacion.radio_tierra * np.outer(np.cos(u), np.sin(v))
    y_tierra = simulacion.radio_tierra * np.outer(np.sin(u), np.sin(v))
    z_tierra = simulacion.radio_tierra * np.outer(np.ones(np.size(u)), np.cos(v))
    colores_tierra = crear_textura_tierra(resolucion)
    eje.plot_surface(x_tierra, y_tierra, z_tierra,
                   facecolors=colores_tierra,
                   shade=True,
                   alpha=0.95,
                   antialiased=True)

    # aqui se dibujan las lineas de campo magnetico

    def lineas_campo_magnetico(eje, num_lineas=8):
        # se definen distintos valores del parametro L para crear distintas lineas
        valores_L = np.linspace(1.5, 5.0, num_lineas)

        for L in valores_L:
            # este es el angulo de latitud magnetica
            lambda_magnetico = np.linspace(-np.pi/2 + 0.1, np.pi/2 - 0.1, 100)

            # este es el radio en funcion de la latitud
            radio = L * np.cos(lambda_magnetico)**2

            # aqui se dibuja la linea en diferentes planos longitudinales
            for theta in [0, np.pi/2, np.pi, 3*np.pi/2]:
                # se pasa a coordenadas cartesianas
                phi = np.pi/2 - lambda_magnetico
                x_campo = radio * np.sin(phi) * np.cos(theta)
                y_campo = radio * np.sin(phi) * np.sin(theta)
                z_campo = radio * np.cos(phi)

                # aqui ya se dibuja la linea
                eje.plot(x_campo, y_campo, z_campo,
                       color='lime',
                       alpha=0.3,
                       linewidth=1.0,
                       linestyle='--')

    lineas_campo_magnetico(eje, num_lineas=6)

    # aqui se definen los objetos necesarios para los electrones
    puntos_electrones = []
    lineas_electrones = []
    for _ in trayectorias_electrones:
        punto = eje.scatter([], [], [], c='red', s=80, marker='o',
                           edgecolors='yellow', linewidths=1.5, alpha=1.0)
        linea, = eje.plot([], [], [], 'red', alpha=0.6, linewidth=2.5)
        puntos_electrones.append(punto)
        lineas_electrones.append(linea)

    # aqui se definen los objetos necesarios para los protones
    puntos_protones = []
    lineas_protones = []
    for _ in trayectorias_protones:
        punto = eje.scatter([], [], [], c='cyan', s=100, marker='o',
                           edgecolors='blue', linewidths=1.5, alpha=1.0)
        linea, = eje.plot([], [], [], 'cyan', alpha=0.6, linewidth=2.5)
        puntos_protones.append(punto)
        lineas_protones.append(linea)

    # ejes, fondo, leyenda, titulos, etc
    radio_maximo = simulacion.radio_cinturon_externo * 1.2
    eje.set_xlim([-radio_maximo, radio_maximo])
    eje.set_ylim([-radio_maximo, radio_maximo])
    eje.set_zlim([-radio_maximo, radio_maximo])
    eje.set_xlabel('X (Radios Terrestres)', fontsize=11, fontweight='bold')
    eje.set_ylabel('Y (Radios Terrestres)', fontsize=11, fontweight='bold')
    eje.set_zlabel('Z (Radios Terrestres)', fontsize=11, fontweight='bold')
    eje.set_title('CINTURONES DE VAN ALLEN\n', fontsize=13, fontweight='bold', pad=20)
    eje.xaxis.pane.fill = False
    eje.yaxis.pane.fill = False
    eje.zaxis.pane.fill = False
    eje.set_facecolor('black')
    figura.patch.set_facecolor('black')
    eje.xaxis.label.set_color('white')
    eje.yaxis.label.set_color('white')
    eje.zaxis.label.set_color('white')
    eje.tick_params(colors='white')
    eje.title.set_color('white')

    from matplotlib.lines import Line2D
    elementos_leyenda = [
        Line2D([0], [0], marker='o', color='w', label='Electrones',
               markerfacecolor='red', markersize=8),
        Line2D([0], [0], marker='o', color='w', label='Protones',
               markerfacecolor='cyan', markersize=8),
        Line2D([0], [0], color='lime', linewidth=2, linestyle='--',
               label='Campo magnetico')
    ]
    eje.legend(handles=elementos_leyenda,
              loc='upper left',
              fontsize=10,
              framealpha=0.8)

    # aqui ya se empieza a definir la animacion
    def inicializar():
        for punto in puntos_electrones + puntos_protones:
            punto._offsets3d = ([], [], [])
        for linea in lineas_electrones + lineas_protones:
            linea.set_data([], [])
            linea.set_3d_properties([])
        return puntos_electrones + puntos_protones + lineas_electrones + lineas_protones

    # aqui es donde se actualizan los frames
    def animar(cuadro):
        longitud_estela = 80

        # aqui se actualizan los electrones
        for i, trayectoria in enumerate(trayectorias_electrones):
            indice = cuadro % len(trayectoria['x'])
            puntos_electrones[i]._offsets3d = (
                [trayectoria['x'][indice]],
                [trayectoria['y'][indice]],
                [trayectoria['z'][indice]]
            )
            indice_inicio = max(0, indice - longitud_estela)
            lineas_electrones[i].set_data(
                trayectoria['x'][indice_inicio:indice+1],
                trayectoria['y'][indice_inicio:indice+1]
            )
            lineas_electrones[i].set_3d_properties(trayectoria['z'][indice_inicio:indice+1])

        # aqui se actualizan los protones
        for i, trayectoria in enumerate(trayectorias_protones):
            indice = cuadro % len(trayectoria['x'])
            puntos_protones[i]._offsets3d = (
                [trayectoria['x'][indice]],
                [trayectoria['y'][indice]],
                [trayectoria['z'][indice]]
            )
            indice_inicio = max(0, indice - longitud_estela)
            lineas_protones[i].set_data(
                trayectoria['x'][indice_inicio:indice+1],
                trayectoria['y'][indice_inicio:indice+1]
            )
            lineas_protones[i].set_3d_properties(trayectoria['z'][indice_inicio:indice+1])

        # esto es para rotar la perspectiva para que se vean todas las simulaciones
        eje.view_init(elev=20, azim=cuadro * 0.5)

        return puntos_electrones + puntos_protones + lineas_electrones + lineas_protones

    # aqui ya se hace la animacion como tal
    num_cuadros = 400
    animacion = FuncAnimation(
        figura,
        animar,
        init_func=inicializar,
        frames=num_cuadros,
        interval=50,
        blit=False,
        repeat=True
    )

    tiempo_final = time.time()
    print(f"Simulacion hecha en {tiempo_final - tiempo_inicio:.2f} segundos")
    try:
        animacion.save(
            'SimulacionVanAllen.gif',
            writer='pillow',
            fps=20,
            dpi=100
        )
        print("Animacion guardada")

    except Exception as e:
        print(f"no se pudo guardo animacion")
    plt.tight_layout()
    plt.show()

# aqui ya se ejecuta la animacion
if __name__ == "__main__":
    simulacion_van_allen()